### ISSUE TITLE
Deprecated endpoints would ideally be marked @deprecated

### ISSUE THREAD

**Issue by filipecatraia** [sendinblue/APIv3-typescript-library#19]
Example: https://github.com/sendinblue/APIv3-typescript-library/blob/master/api/transactionalEmailsApi.ts#L1302

Just a suggestion that would make everyone's life easier :)

**Comment by aayush-sib** [comment]
Hi @filipecatraia 
Thanks for pointing this. We will update the file with changes in the next release.
