### ISSUE TITLE
readme example using import doesnt work

### ISSUE THREAD

**Issue by dyllandry** [sendinblue/APIv3-typescript-library#20]
The following throws an error: `Property 'authentications' is protected and only accessible within class 'AccountApi' and its subclasses.`

```typescript
import SibApiV3Sdk from 'sib-api-v3-typescript';
let apiInstance = new SibApiV3Sdk.AccountApi()
// Configure API key authorization: api-key
let apiKey = apiInstance.authentications['apiKey'];
apiKey.apiKey = "YOUR API KEY"
```

What works for me is the following:

```typescript
import SibApiV3Sdk from 'sib-api-v3-typescript';
let apiInstance = new SibApiV3Sdk.AccountApi()
// Configure API key authorization: api-key
apiInstance.setApiKey(SibApiV3Sdk.AccountApiApiKeys.apiKey, '<put your api key here>');
```

**Comment by aayush-sib** [comment]
Hi @dyllandry 
Thanks for pointing out this issue. We will update the doc with this change. Sorry for the inconvenience.

**Comment by bananer** [comment]
Hi! I just came across this and wanted to gently remind you that the readme still contains the invalid code example.

Solution by @dyllandry seems to be good, thanks for that!
