### ISSUE TITLE
Authentication key protected.

### ISSUE THREAD

**Issue by dkluhzeb** [sendinblue/APIv3-typescript-library#22]
Hi,

I want to move to the typescript SDK and have a problem to implement the authentication like it is documented.

If i follow the instructions:

![Screenshot_20210211_124007](https://user-images.githubusercontent.com/7802258/107632591-fce0ff80-6c66-11eb-8071-0d9f53a02c3f.png)

I get an error that the authentications property is protected:
![Screenshot_20210211_123830](https://user-images.githubusercontent.com/7802258/107632720-2a2dad80-6c67-11eb-8e6a-dbbfb3298923.png)

Thats true:
![Screenshot_20210211_123701](https://user-images.githubusercontent.com/7802258/107632752-34e84280-6c67-11eb-8a77-e285461e442e.png)

Is there a proper way to pass my auth key?

**Comment by aayush-sib** [comment]
Hi @dkluhzeb 
You can use this function `apiInstance.setApiKey(SibApiV3Sdk.AccountApiApiKeys.apiKey, 'YOUR API KEY');` to set your API-key. Sorry for the inconvenience we will fix this issue in our reference dock.

**Comment by cnpatric** [comment]
3 months and the example provided in the readme still shows this.

Why close the issue if you didn't fix it?

**Comment by aayush-sib** [comment]
Hi @cnpatric 
I am sorry for the inconvenience, it got lost from my list. Will fix it ASAP.
Reopening the issue again

**Comment by aayush-sib** [comment]
Hi 

I have updated the readme here, will update the readme in npm in the next release. Sorry for the inconvenience we will fix this issue in our reference document also.

Thanks!
