### ISSUE TITLE
Property 'authentications' is protected and only accessible within class 'TransactionalEmailsApi' and its subclasses

### ISSUE THREAD

**Issue by ChuckJonas** [sendinblue/APIv3-typescript-library#41]
Trying to use the typescript example provided [in your transactional docs](https://developers.sendinblue.com/reference/sendtransacemail), and I get a type error...

<img width="647" alt="hello_ts_—_balsamroot-site" src="https://user-images.githubusercontent.com/5217568/142708912-d13681af-2447-41c0-8d3b-d66bbc99cd85.png">

It's worth noting that your example actually does "compile" because it uses `const  SibApiV3Sdk = require('sib-api-v3-typescript');` instead of `import SibApiV3Sdk from 'sib-api-v3-typescript';`.  But what's the point of using typescript if you just "require" it (you lose the types).

The fact that there is a separate library for typescript is actually kinda weird... Why not just DefinitelyTyped?

**Comment by ChuckJonas** [comment]
I just looked at the readme for this project and it looks like a totally different package...

Are the docs are on the site and NPM just out of date?

Should I be using `@sendinblue/client`?

**Comment by aayush-sib** [comment]
Hi @ChuckJonas 
I think we missed updating the link in our documentation.
You can now use `@sendinblue/client` package.

Also, we are planning to improve our Node.js package.
