### ISSUE TITLE
Batch update endpoint not supported

### ISSUE THREAD

**Issue by flipswitchingmonkey** [sendinblue/APIv3-typescript-library#42]
It looks like the batch update endpoint is not part of the library?

This one: https://developers.sendinblue.com/reference/updatebatchcontacts

**Comment by aayush-sib** [comment]
Hi @flipswitchingmonkey 

Yes, currently it is not supported in this wrapper, you can do an HTTP request for this functionality from your application. We will soon update our all wrappers with the latest changes. Sorry for the inconvenience.

**Comment by LeandroDoldan** [comment]
Hi! Any news here? It's been 1.5 years and it would be really cool to have this endpoint added.
