### ISSUE TITLE
getEmailCampaign method doesn't serialize statistics

### ISSUE THREAD

**Issue by Sylphide** [sendinblue/APIv3-typescript-library#53]
Hello,

As the title suggest the method getEmailCampaign doesn't parse api results correctly and some attributes are missing.
When I manually call the api endpoint `/emailCampaigns/{campaignId}` I get what is expected from the documentation, on the other hand, the method from the library omits some datas (i.e. `statistics` in my case).

Thanks

**Comment by aayush-sib** [comment]
Hi @Sylphide 
Thanks for reporting it, I will look into this issue.

**Comment by aayush-sib** [comment]
Hi @Sylphide 
We have released a new version to fix this issue. Sorry for the inconvenience.
