### ISSUE TITLE
scheduledAt option has the wrong type in api.d.ts

### ISSUE THREAD

**Issue by aivanov-noveo** [sendinblue/APIv3-typescript-library#55]
## Description

`scheduledAt` has the `Date` type while the `sendTransacEmail` expects it to be a strring in RFC-3339 format.
```typescript
    'scheduledAt'?: Date;
```

## Environment

    @sendinblue/client v3.2.2

## Workaround

To pass `scheduledAt` like this:
```typescript
scheduledAt: scheduledAt as any as Date
```

**Comment by to7be** [comment]
I'm also struggling with this. I've tried several different formats, including the function `formatRFC3339` of the `date-fns` library, to first format and then parse a Date-object which would work.

Thanks for the workaround @aivanov-noveo, this way it works for me.

**Comment by aayush-sib** [comment]
Hi
We have fixed this in the latest release
