### ISSUE TITLE
Create contact attribute - parameter isRecurring is missing in definition

### ISSUE THREAD

**Issue by gitdast** [sendinblue/APIv3-typescript-library#62]
https://developers.sendinblue.com/reference/createattribute-1
Too add parameter `isRecurring` is not possible because of missing definition.
Error: **Property 'isRecurring' does not exist on type 'CreateAttribute'.**

**Comment by aayush-sib** [comment]
Hi
We have added this in the latest release

**Comment by gitdast** [comment]
Thank you. But there are BC changes like AttributesApi >> AccountApi, ...
