### ISSUE TITLE
Dependency update: 2 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by acomanescu** [sendinblue/APIv3-typescript-library#65]
Are you planning to replace "request" with "fetch" (now available in Node.js by default)

```
# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
No fix available
node_modules/request
  @sendinblue/client  *
  Depends on vulnerable versions of request
  node_modules/@sendinblue/client

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

**Comment by Charlygraphy23** [comment]
request package can be converted to [node-fetch](https://www.npmjs.com/package/node-fetch) or [axios](https://www.npmjs.com/package/axios). team you can assign to me for this task

**Comment by shivpratik** [comment]
Please fix this issue.

**Comment by alfaproject** [comment]
Honestly guys, if this package is not maintained just let us know so we can build our own bindings

**Comment by psychonetic** [comment]
When can we expect to get the PR merged?

**Comment by Charlygraphy23** [comment]
> Using now Brevo commercially, it seems important to me to remove the deprecated lib.

Hey @psychonetic please use  Brevo. This is going to be deprecated.

**Comment by alfaproject** [comment]
Is there a new Brevo SDK now?

**Comment by psychonetic** [comment]
@alfaproject 
Yes: https://github.com/getbrevo/brevo-node

Typescript is not fully supported yet and it seems like there are also issues with attachments. 
So not really production ready. Hope they will manage to update the SDK soon.
